# Generated by Django 4.0.4 on 2022-06-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcontact',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
