# Generated by Django 4.0.4 on 2022-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycole', '0004_ourwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourwork',
            name='number',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
