# Generated by Django 4.0.4 on 2022-06-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tycole', '0005_ourwork_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourwork',
            name='date',
        ),
    ]
