# Generated by Django 4.0.4 on 2023-01-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tycole', '0007_ourwork_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourwork',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ourwork',
            old_name='number',
            new_name='name',
        ),
    ]
