# Generated by Django 4.0.4 on 2023-01-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tycole', '0008_rename_img_ourwork_image_rename_number_ourwork_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourwork',
            name='name',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
